# Generated by Django 4.0.5 on 2022-07-03 16:24

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_categorias_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorias',
            name='image',
        ),
        migrations.RemoveField(
            model_name='categorias',
            name='website',
        ),
        migrations.AddField(
            model_name='homepage',
            name='categories',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='home.categorias'),
        ),
        migrations.AlterField(
            model_name='categoriasordenables',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoria_noticia', to='home.blogdetailpage'),
        ),
    ]
