# Generated by Django 4.0.5 on 2022-07-03 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_categorias_image_remove_categorias_website_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(allow_unicode=True, max_length=255, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'Categoría de noticia',
                'verbose_name_plural': 'Categorías de noticias',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='categoriasordenables',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='categoriasordenables',
            name='page',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='categories',
        ),
        migrations.DeleteModel(
            name='Categorias',
        ),
        migrations.DeleteModel(
            name='CategoriasOrdenables',
        ),
    ]
