# Generated by Django 4.0.5 on 2022-07-03 21:08

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_newscategory_remove_categoriasordenables_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogdetailpage',
            name='categories',
            field=modelcluster.fields.ParentalManyToManyField(to='home.newscategory'),
        ),
    ]
