# Generated by Django 4.0.5 on 2022-07-04 02:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_blogdetailpage_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogdetailpage',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Post date'),
            preserve_default=False,
        ),
    ]
