# Generated by Django 4.0.5 on 2022-07-04 04:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_blogdetailpage_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogdetailpage',
            name='date',
        ),
        migrations.AddField(
            model_name='blogdetailpage',
            name='publication_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='post date'),
            preserve_default=False,
        ),
    ]
