# Generated by Django 4.0.5 on 2022-07-04 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_blogdetailpage_created_at_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogdetailpage',
            old_name='created_at_order',
            new_name='created_at_date',
        ),
        migrations.RenameField(
            model_name='blogdetailpage',
            old_name='created_at',
            new_name='created_at_date_time',
        ),
    ]
